#NumPy Arrays

In [2]:
my_list = [1,2,3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [31]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [35]:
np.random.rand() #0to1

0.24202174559053158

In [37]:
np.random.rand(5,5)

array([[0.97989057, 0.03392548, 0.5004239 , 0.95024944, 0.34491338],
       [0.43886089, 0.43329686, 0.54526464, 0.23513193, 0.98587742],
       [0.00336189, 0.49128907, 0.48809346, 0.52651443, 0.84977021],
       [0.73729554, 0.64206124, 0.43124206, 0.80571127, 0.53550762],
       [0.03214886, 0.47121859, 0.99302286, 0.499105  , 0.6227879 ]])

In [41]:
np.random.randn(2)

array([-0.2989093,  0.147715 ])

In [43]:
np.random.randn(2,2)

array([[-0.49603252, -1.47413653],
       [-0.43049413, -0.32084699]])

In [47]:
np.random.randint(1,100,10)

array([ 7, 90, 53, 45, 13, 69, 70, 12, 22, 40])

In [49]:
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [53]:
ranarr = np.random.randint(0,50,10)

In [55]:
ranarr

array([ 8, 29, 10,  2, 35, 27, 42,  0, 30, 30])

In [83]:
arr.reshape(5,5)

In [59]:
ranarr.max()

42

In [63]:
ranarr.min()

0

In [65]:
ranarr.argmax()

6

In [67]:
ranarr.argmin()


7

In [85]:
arr=arr.reshape(5,5)

In [87]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
arr.shape

(5, 5)

In [91]:
arr.dtype

dtype('int32')

In [93]:
ranarr.dtype

dtype('int32')

In [95]:
from numpy.random import randint


In [97]:
randint(2,10)

5

NumPy Idexing and Selection

In [99]:
import numpy as np

In [109]:
arr = np.arange(0,11) #indexing starts from 0

In [103]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [111]:
arr[8] #since indexing start from 0 in index 8 it is value 8

8

In [107]:
arr[1:5]

array([1, 2, 3, 4])

In [113]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [115]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [117]:
arr[0:5]=100

In [119]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [131]:
arr=np.arange(0,11)

In [133]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [135]:
slice_of_arr = arr[0:6]

In [137]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [141]:
slice_of_arr[:]=99

In [143]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [145]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [147]:
arr_copy=arr.copy()

In [149]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [153]:
arr_copy[:]=100

In [155]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [157]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

2D Array

In [163]:
import numpy as np

In [165]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [167]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [187]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [189]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [191]:
arr = np.arange(1,11)

In [193]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [197]:
bool_arr=arr>5

In [199]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [203]:
arr[bool_arr] #return only true

array([ 6,  7,  8,  9, 10])

In [205]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [207]:
arr[arr<3]

array([1, 2])

In [209]:
arr_2d = np.arange(50).reshape(5,10)

In [217]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [215]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

Numpy Operations

In [219]:
arr = np.arange(0,11)

In [221]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [223]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [225]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [227]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [233]:
arr*100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [237]:
arr / arr #1/0

C:\Users\Acer\AppData\Local\Temp\ipykernel_25544\724776829.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr #1/0


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [239]:
1/arr

C:\Users\Acer\AppData\Local\Temp\ipykernel_25544\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [243]:
arr **2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [245]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [247]:
np.max(arr)

10